package agentembed

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"io/fs"
)

// Prebuilt guest binaries, compiled at release time and embedded so a user
// never needs a Go toolchain to boot a sandbox.
//
// The directory is EMPTY in git (just .gitkeep and a README) — the payload is
// generated by `make guestbin` and gitignored. That keeps ~7 MiB of binaries
// out of the history and, more importantly, keeps them from going stale: a
// source install builds the guest binaries from the embedded .in sources as it
// always has, so a contributor editing init_main.go.in gets their edit rather
// than a committed artifact from three months ago.
//
// So there are two shapes of clawk binary:
//
//   - release artifact — `make guestbin` ran first, the binaries are embedded,
//     and nothing needs `go` at runtime;
//   - source build (`make install`, `go build`) — nothing embedded, and
//     guestbuild compiles from source on first boot, exactly as before.
//
// all: so the embed pattern still matches when the dir holds only dotfiles;
// without it `go:embed prebuilt` would fail to compile on a clean checkout.
//
//go:embed all:prebuilt
var prebuiltFS embed.FS

// PrebuiltDir is where `make guestbin` writes, relative to this package.
const PrebuiltDir = "prebuilt"

// PrebuiltManifestName identifies the metadata `make guestbin` writes beside
// the binaries.
const PrebuiltManifestName = "manifest.json"

// PrebuiltManifest describes what the embedded binaries are, so a consumer can
// refuse a set that doesn't match what it needs.
type PrebuiltManifest struct {
	// Arch is the GOARCH the binaries were built for. Guest arch always
	// equals host arch (hardware virtualization can't cross architectures),
	// but recording it means a mismatch is caught rather than assumed.
	Arch string `json:"arch"`

	// SourcesSHA256 is SourcesHash() at build time. It is the one thing worth
	// verifying: it catches an artifact whose embedded binaries were built
	// from different .in sources than the ones embedded beside them, which is
	// otherwise invisible and would ship a guest that silently predates the
	// source tree.
	SourcesSHA256 string `json:"sources_sha256"`

	// GoVersion built them, for diagnostics.
	GoVersion string `json:"go_version,omitempty"`
}

// SourcesHash digests every embedded guest source, in a fixed order. Both the
// generator and the consumer compute it the same way, so it can be compared
// across a build boundary.
func SourcesHash() string {
	h := sha256.New()
	for _, s := range []struct {
		name string
		data []byte
	}{
		{"clawk-init/main.go", InitMainGo},
		{"clawk-init/go.mod", InitGoMod},
		{"clawk-pty-agent/main.go", AgentMainGo},
		{"clawk-pty-agent/go.mod", AgentGoMod},
		{"clawk-time-sync/main.go", TimeSyncMainGo},
		{"clawk-time-sync/go.mod", TimeSyncGoMod},
	} {
		h.Write([]byte(s.name))
		h.Write(s.data)
	}
	return hex.EncodeToString(h.Sum(nil))
}

// Prebuilt returns the embedded binaries and their manifest.
//
// ok is false for an ordinary source build, where the directory holds no
// payload — that is the normal case for contributors, not an error.
func Prebuilt() (files fs.FS, m PrebuiltManifest, ok bool) {
	sub, err := fs.Sub(prebuiltFS, PrebuiltDir)
	if err != nil {
		return nil, PrebuiltManifest{}, false
	}
	data, err := fs.ReadFile(sub, PrebuiltManifestName)
	if err != nil {
		return nil, PrebuiltManifest{}, false
	}
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, PrebuiltManifest{}, false
	}
	return sub, m, true
}
